### ISSUE TITLE
Cannot access env variables from the executed app

### ISSUE THREAD

**Issue by DrumSergio** [rocker-org/shiny#61] opened 2019-03-21 14:10 UTC
Let's suppose the following dockerfile. The app.R is then inside `/srv/shiny-server`

```
FROM rocker/shiny

RUN apt-get update && apt-get upgrade -y && apt-get install -y libv8-dev libssl-dev

RUN R -e "install.packages(c('shinydashboard', 'DT', 'shinyWidgets', 'shinyFiles', 'diffobj', 'shinyjqui', 'shinyjs', 'V8', 'RSQLite', 'DBI', 'generator', 'dplyr', 'randNames'))"

RUN rm -rf /srv/shiny-server/*
COPY . /srv/shiny-server/

EXPOSE 3838
CMD ["/usr/bin/shiny-server.sh"]
```

I am using ShinyProxy to initialize the container. It passes the env variable SHINYPROXY_USERNAME to the root user. But somehow the app can't read it, so the app doesn't know who's the person logged in.

Inside the app.R I've put the following JS alert:
`alert(system("whoami"))`

And it outputs just "0". That's not even a user. So how can that user have access to the environmental variables of "root"? Something needs to be done! Is really "0" the user running the app? I doubt so

Do you know how can I get rid of this problem, so the app can know the user logged in? Thanks

EDIT: This comes from https://support.openanalytics.eu/t/shinyproxy-username-in-shiny-user/1038

**Comment by cboettig** [comment] 2019-03-21 16:38
You seem to be running as root; unless you've specified a `--user` option in your `docker run` command or add `USER` to your Dockerfile?  

Note that it would be helpful to understand your issue if you include enough details to reproduce the behavior.  You haven't told us what is in `.` that you're copying, or what `docker run` command options you are using

**Comment by eddelbuettel** [comment] 2019-03-21 17:42
Also, as you mention the proxy by OpenAnalytics:  are we sure there isn't another machine in between?  Can you cook up an example with just our Rocker container?  Else we cannot reproduce...

**Comment by DrumSergio** [comment] 2019-03-21 19:12
Ok, so let's do it:

We download these docker containers of my repo, they are public:

```
docker pull acsdesk/shinyproxy-demo
docker pull acsdesk/example-username
```

We create a network and we run it:

```
docker network create shinyproxy-net
docker run -d -v /var/run/docker.sock:/var/run/docker.sock --net shinyproxy-net -p 8080:8080 acsdesk/shinyproxy-demo
```

I hope the Dockerfiles will get uploaded to https://cloud.docker.com/repository/docker/acsdesk/example-username/ and
https://cloud.docker.com/repository/docker/acsdesk/shinyproxy-demo if not, they connect to my GitHub project: https://github.com/DrumSergio/shinyproxy-example so if you want to build the containers yourself you have both dockerfiles there.

We can access to the web using the username "test" and password "test": http://localhost:8080
And the code I've prepared is here: https://github.com/DrumSergio/shinyproxy-example/blob/master/example-username/app.R

You can see it's not working right now

Thank you!

**Comment by cboettig** [comment] 2019-03-22 17:11
Apologies, but I'm really not familiar with ShinyProxy so I cannot follow what is going on here.  From a quick look, https://www.shinyproxy.io/ does not seem to be based on RStudio's Shiny Server (provided by this package), but has taken a different route by implementing some java wrapper around the shiny R package(?)  It's not obvious to me that shinyproxy is meant to work in this context, but I think you would be better off following up with them on this issue.  

Of course, you can put a reverse proxy server in front of any containerized service, and for an enterprise environment RStudio already provides Shiny Server Pro.  (I realize that is a paid product -- we are grateful for RStudio's agreement for us to package the open source shiny server in Rocker and are not interested in providing alternatives to their enterprise products).

So I'm afraid I'll close this out as we cannot really be of any help here!  Best of luck.

**Closed by cboettig** 2019-03-22 17:11 UTC

**Comment by tverbeke** [comment] 2019-03-23 08:23
ShinyProxy is indeed not meant to work with a Shiny Server Docker image since it is in itself a complete open source solution for hosting Shiny apps in an enterprise context and only requires the presence of R and Shiny in the container. All of this is documented in the [getting started guide](https://www.shinyproxy.io/getting-started/) and the section on [deploying apps](https://www.shinyproxy.io/deploying-apps/). When following the documentation it will be possible to access the `SHINYPROXY_USERNAME` environment variable using `Sys.getenv`.
