### ISSUE TITLE
Permission denied when running rocker/shiny-verse and rocker/shiny images

### ISSUE THREAD

**Issue by nayefahmad** [rocker-org/shiny#78] opened 2020-05-17 01:46 UTC
I'm trying to run Shiny Server on an EC2 instance running Ubuntu.

Following [this page](https://hub.docker.com/r/rocker/shiny), I run this command: `docker run --rm -p 3838:3838 rocker/shiny`.

I get the following warning and error:

`s6-supervise shiny-server: warning: unable to spawn ./run - waiting 10 seconds`

`s6-supervise (child): fatal: unable to exec run: Exec format error`

After that, those two outputs just repeat every 10 seconds. I can't even kill the process, so I have to close the terminal and start another one.

I'm new to Docker and have no real clue how to proceed from here. Any help would be appreciated.

**Comment by cboettig** [comment] 2020-05-18 00:25
@noamross can you take a look at this when you have a chance?

**Comment by noamross** [comment] 2020-05-19 02:01
Hello @nayefahmed, thanks for the report.  I am unable to reproduce this error, but I did make a change that should make you able to kill the process.  Could you pull the latest image with  `docker pull rocker/shiny` and try again?

**Comment by ssinari** [comment] 2020-09-28 20:48
Hello,
I am running into this permission denied issue as well. Would like to update you about this. The command that runs is shown on the last line. The current directory has the flexdashboard rmarkdown file that renders as a shiny dashboard:
![Screenshot from 2020-09-28 13-42-34](https://user-images.githubusercontent.com/3277981/94484214-e8f1a100-0190-11eb-8bfc-d9ea440bd0e5.png)

**Comment by eitsupi** [comment] 2022-02-21 14:44
Since there is no reply, I will close this issue.

@ssinari I think this is a different issue, a general Docker permission problem.
Instead of bind-mounting `$(pwd)` to `/srv/shiny-server/`, consider bind-mounting the subdirectory as read-only. e.g. `-v shinyapp/:/srv/shiny-server/shinyapp/:ro`

**Closed by eitsupi** 2022-02-21 14:44 UTC
